In [2]:
import pandas as pd
df = pd.read_csv("../data/raw/Matches.csv")
df.head()

C:\Users\alexl\AppData\Local\Temp\ipykernel_32384\967385704.py:2: DtypeWarning: Columns (0: MatchTime) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/raw/Matches.csv")

,Division,MatchDate,MatchTime,HomeTeam,AwayTeam,HomeElo,AwayElo,Form3Home,Form5Home,Form3Away,...,MaxUnder25,HandiSize,HandiHome,HandiAway,C_LTH,C_LTA,C_VHD,C_VAD,C_HTB,C_PHB
0,F1,2000-07-28,NaN,Marseille,Troyes,1686.34,1586.57,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,F1,2000-07-28,NaN,Paris SG,Strasbourg,1714.89,1642.51,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,F2,2000-07-28,NaN,Wasquehal,Nancy,1465.08,1633.80,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,F1,2000-07-29,NaN,Auxerre,Sedan,1635.58,1624.22,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,F1,2000-07-29,NaN,Bordeaux,Metz,1734.34,1673.11,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
def get_season(date):
    if date.month >= 8:
        return f"{date.year}/{str(date.year + 1)[-2:]}"
    else:
        return f"{date.year - 1}/{str(date.year)[-2:]}"

df["MatchDate"] = pd.to_datetime(df["MatchDate"], dayfirst=True)
df["Season"] = df["MatchDate"].apply(get_season)

C:\Users\alexl\AppData\Local\Temp\ipykernel_32384\4269469720.py:7: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df["MatchDate"] = pd.to_datetime(df["MatchDate"], dayfirst=True)

In [7]:
seasons = [
    "2015/16",
    "2016/17",
    "2017/18",
    "2018/19",
    "2019/20",
    "2020/21",
    "2021/22",
    "2022/23",
    "2023/24",
    "2024/25"
]
df = df[df["Season"].isin(seasons)]
prem_df = df[df["Division"] == "E0"]
prem_df.head()

,Division,MatchDate,MatchTime,HomeTeam,AwayTeam,HomeElo,AwayElo,Form3Home,Form5Home,Form3Away,...,HandiSize,HandiHome,HandiAway,C_LTH,C_LTA,C_VHD,C_VAD,C_HTB,C_PHB,Season
114226,E0,2015-08-08,NaN,Bournemouth,Aston Villa,1597.08,1580.38,7.0,13.0,3.0,...,-0.5,1.93,1.92,0.0594,0.1948,0.2077,0.0267,0.3183,0.1930,2015/16
114227,E0,2015-08-08,NaN,Chelsea,Swansea,1893.44,1673.08,4.0,10.0,3.0,...,-1.5,2.16,1.73,0.2955,0.1524,0.4327,0.0100,0.0833,0.0262,2015/16
114228,E0,2015-08-08,NaN,Everton,Watford,1709.04,1576.56,3.0,6.0,7.0,...,-1.0,2.18,1.71,0.0426,0.1409,0.0903,0.0149,0.5482,0.1631,2015/16
114229,E0,2015-08-08,NaN,Leicester,Sunderland,1636.10,1607.61,7.0,10.0,2.0,...,-0.5,1.95,1.90,0.0461,0.8358,0.0268,0.0227,0.0317,0.0370,2015/16
114230,E0,2015-08-08,NaN,Man United,Tottenham,1812.81,1733.16,5.0,5.0,6.0,...,-1.0,2.09,1.78,0.0257,0.2872,0.0167,0.0653,0.2419,0.3632,2015/16

In [8]:
columns_to_keep = [
    "MatchDate",
    "HomeTeam",
    "AwayTeam",
    "HomeElo",
    "AwayElo",
    "Form3Home",
    "Form5Home",
    "Form3Away",
    "Form5Away",
    "FTHome",
    "FTAway",
    "FTResult"
]

prem_df = prem_df[columns_to_keep].copy()
prem_df.head()

,MatchDate,HomeTeam,AwayTeam,HomeElo,AwayElo,Form3Home,Form5Home,Form3Away,Form5Away,FTHome,FTAway,FTResult
114226,2015-08-08,Bournemouth,Aston Villa,1597.08,1580.38,7.0,13.0,3.0,6.0,0.0,1.0,A
114227,2015-08-08,Chelsea,Swansea,1893.44,1673.08,4.0,10.0,3.0,9.0,2.0,2.0,D
114228,2015-08-08,Everton,Watford,1709.04,1576.56,3.0,6.0,7.0,13.0,2.0,2.0,D
114229,2015-08-08,Leicester,Sunderland,1636.10,1607.61,7.0,10.0,2.0,8.0,4.0,2.0,H
114230,2015-08-08,Man United,Tottenham,1812.81,1733.16,5.0,5.0,6.0,7.0,1.0,0.0,H

In [9]:
prem_df.isnull().sum()

MatchDate    0
HomeTeam     0
AwayTeam     0
HomeElo      1
AwayElo      1
Form3Home    0
Form5Home    0
Form3Away    0
Form5Away    0
FTHome       0
FTAway       0
FTResult     0
dtype: int64

In [10]:
prem_df = prem_df.dropna(subset=["HomeElo", "AwayElo"])
prem_df.isnull().sum()

MatchDate    0
HomeTeam     0
AwayTeam     0
HomeElo      0
AwayElo      0
Form3Home    0
Form5Home    0
Form3Away    0
Form5Away    0
FTHome       0
FTAway       0
FTResult     0
dtype: int64

In [11]:
prem_df.duplicated().sum()

np.int64(0)

In [12]:
prem_df["FTResult"].value_counts()

FTResult
H    1690
A    1222
D     886
Name: count, dtype: int64

In [13]:
prem_df.describe()

,MatchDate,HomeElo,AwayElo,Form3Home,Form5Home,Form3Away,Form5Away,FTHome,FTAway
count,3798,3798.00000,3798.000000,3798.000000,3798.000000,3798.000000,3798.000000,3798.000000,3798.000000
mean,2020-07-07 19:09:57.156398,1747.06550,1747.030408,4.083728,6.873881,4.268299,7.097683,1.552396,1.278304
min,2015-08-08 00:00:00,1499.79000,1475.480000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2017-12-23 18:00:00,1656.23000,1656.325000,2.000000,4.000000,3.000000,4.000000,1.000000,0.000000
50%,2020-07-26 00:00:00,1726.16500,1724.785000,4.000000,7.000000,4.000000,7.000000,1.000000,1.000000
75%,2023-01-18 18:00:00,1826.26000,1826.240000,6.000000,9.000000,6.000000,10.000000,2.000000,2.000000
max,2025-05-25 00:00:00,2090.14000,2090.140000,9.000000,15.000000,9.000000,15.000000,9.000000,9.000000
std,NaN,117.03921,117.212213,2.530060,3.506816,2.502335,3.480135,1.321713,1.213656

In [19]:
sorted(prem_df["HomeTeam"].unique())

['Arsenal',
 'Aston Villa',
 'Bournemouth',
 'Brentford',
 'Brighton',
 'Burnley',
 'Cardiff',
 'Chelsea',
 'Crystal Palace',
 'Everton',
 'Fulham',
 'Huddersfield',
 'Hull',
 'Ipswich',
 'Leeds',
 'Leicester',
 'Liverpool',
 'Luton',
 'Man City',
 'Man United',
 'Middlesbrough',
 'Newcastle',
 'Norwich',
 "Nott'm Forest",
 'Nottm Forest',
 'Sheffield United',
 'Southampton',
 'Stoke',
 'Sunderland',
 'Swansea',
 'Tottenham',
 'Watford',
 'West Brom',
 'West Ham',
 'Wolves']

In [20]:
sorted(prem_df["AwayTeam"].unique())

['Arsenal',
 'Aston Villa',
 'Bournemouth',
 'Brentford',
 'Brighton',
 'Burnley',
 'Cardiff',
 'Chelsea',
 'Crystal Palace',
 'Everton',
 'Fulham',
 'Huddersfield',
 'Hull',
 'Ipswich',
 'Leeds',
 'Leicester',
 'Liverpool',
 'Luton',
 'Man City',
 'Man United',
 'Middlesbrough',
 'Newcastle',
 'Norwich',
 "Nott'm Forest",
 'Nottm Forest',
 'Sheffield United',
 'Southampton',
 'Stoke',
 'Sunderland',
 'Swansea',
 'Tottenham',
 'Watford',
 'West Brom',
 'West Ham',
 'Wolves']

In [24]:
team_name_fixes = {
    "Nott'm Forest": "Nottm Forest",
}
prem_df["HomeTeam"] = prem_df["HomeTeam"].replace(team_name_fixes)
prem_df["AwayTeam"] = prem_df["AwayTeam"].replace(team_name_fixes)

sorted(prem_df["HomeTeam"].unique())

['Arsenal',
 'Aston Villa',
 'Bournemouth',
 'Brentford',
 'Brighton',
 'Burnley',
 'Cardiff',
 'Chelsea',
 'Crystal Palace',
 'Everton',
 'Fulham',
 'Huddersfield',
 'Hull',
 'Ipswich',
 'Leeds',
 'Leicester',
 'Liverpool',
 'Luton',
 'Man City',
 'Man United',
 'Middlesbrough',
 'Newcastle',
 'Norwich',
 'Nottm Forest',
 'Sheffield United',
 'Southampton',
 'Stoke',
 'Sunderland',
 'Swansea',
 'Tottenham',
 'Watford',
 'West Brom',
 'West Ham',
 'Wolves']

In [25]:
prem_df.to_csv("../data/processed/clean_matches.csv", index=False)