In [1]:
import pandas as pd
df = pd.read_csv("../data/raw/Matches.csv")
df.head()

C:\Users\alexl\AppData\Local\Temp\ipykernel_36692\967385704.py:2: DtypeWarning: Columns (0: MatchTime) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/raw/Matches.csv")

,Division,MatchDate,MatchTime,HomeTeam,AwayTeam,HomeElo,AwayElo,Form3Home,Form5Home,Form3Away,...,MaxUnder25,HandiSize,HandiHome,HandiAway,C_LTH,C_LTA,C_VHD,C_VAD,C_HTB,C_PHB
0,F1,2000-07-28,NaN,Marseille,Troyes,1686.34,1586.57,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,F1,2000-07-28,NaN,Paris SG,Strasbourg,1714.89,1642.51,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,F2,2000-07-28,NaN,Wasquehal,Nancy,1465.08,1633.80,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,F1,2000-07-29,NaN,Auxerre,Sedan,1635.58,1624.22,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,F1,2000-07-29,NaN,Bordeaux,Metz,1734.34,1673.11,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
df.columns.tolist()

['Division',
 'MatchDate',
 'MatchTime',
 'HomeTeam',
 'AwayTeam',
 'HomeElo',
 'AwayElo',
 'Form3Home',
 'Form5Home',
 'Form3Away',
 'Form5Away',
 'FTHome',
 'FTAway',
 'FTResult',
 'HTHome',
 'HTAway',
 'HTResult',
 'HomeShots',
 'AwayShots',
 'HomeTarget',
 'AwayTarget',
 'HomeFouls',
 'AwayFouls',
 'HomeCorners',
 'AwayCorners',
 'HomeYellow',
 'AwayYellow',
 'HomeRed',
 'AwayRed',
 'OddHome',
 'OddDraw',
 'OddAway',
 'MaxHome',
 'MaxDraw',
 'MaxAway',
 'Over25',
 'Under25',
 'MaxOver25',
 'MaxUnder25',
 'HandiSize',
 'HandiHome',
 'HandiAway',
 'C_LTH',
 'C_LTA',
 'C_VHD',
 'C_VAD',
 'C_HTB',
 'C_PHB']

In [3]:
def get_season(date):
    if date.month >= 8:
        return f"{date.year}/{str(date.year + 1)[-2:]}"
    else:
        return f"{date.year - 1}/{str(date.year)[-2:]}"

df["MatchDate"] = pd.to_datetime(df["MatchDate"], dayfirst=True)
df["Season"] = df["MatchDate"].apply(get_season)

C:\Users\alexl\AppData\Local\Temp\ipykernel_36692\4269469720.py:7: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df["MatchDate"] = pd.to_datetime(df["MatchDate"], dayfirst=True)

In [4]:
prem_df = df[df["Division"] == "E0"]
prem_df = prem_df.sort_values("MatchDate").reset_index(drop=True)
prem_df.head()

,Division,MatchDate,MatchTime,HomeTeam,AwayTeam,HomeElo,AwayElo,Form3Home,Form5Home,Form3Away,...,HandiSize,HandiHome,HandiAway,C_LTH,C_LTA,C_VHD,C_VAD,C_HTB,C_PHB,Season
0,E0,2000-08-19,NaN,Charlton,Man City,1608.77,1579.99,0.0,0.0,0.0,...,NaN,NaN,NaN,0.1396,0.0346,0.2085,0.0100,0.2939,0.3134,2000/01
1,E0,2000-08-19,NaN,Chelsea,West Ham,1800.17,1681.36,0.0,0.0,0.0,...,NaN,NaN,NaN,0.0702,0.0742,0.0099,0.0823,0.0387,0.7247,2000/01
2,E0,2000-08-19,NaN,Coventry,Middlesbrough,1635.61,1679.18,0.0,0.0,0.0,...,NaN,NaN,NaN,0.8114,0.0316,0.0103,0.0731,0.0319,0.0417,2000/01
3,E0,2000-08-19,NaN,Derby,Southampton,1636.08,1630.02,0.0,0.0,0.0,...,NaN,NaN,NaN,0.0272,0.0390,0.0467,0.0100,0.0961,0.7810,2000/01
4,E0,2000-08-19,NaN,Leeds,Everton,1782.55,1685.55,0.0,0.0,0.0,...,NaN,NaN,NaN,0.7772,0.0994,0.0140,0.0429,0.0119,0.0546,2000/01

In [5]:
columns_to_keep = [
    "Season",
    "MatchDate",
    "HomeTeam",
    "AwayTeam",
    "Form3Home",
    "Form5Home",
    "Form3Away",
    "Form5Away",
    "FTHome",
    "FTAway",
    "FTResult"
]

prem_df = prem_df[columns_to_keep].copy()
prem_df.head()

,Season,MatchDate,HomeTeam,AwayTeam,Form3Home,Form5Home,Form3Away,Form5Away,FTHome,FTAway,FTResult
0,2000/01,2000-08-19,Charlton,Man City,0.0,0.0,0.0,0.0,4.0,0.0,H
1,2000/01,2000-08-19,Chelsea,West Ham,0.0,0.0,0.0,0.0,4.0,2.0,H
2,2000/01,2000-08-19,Coventry,Middlesbrough,0.0,0.0,0.0,0.0,1.0,3.0,A
3,2000/01,2000-08-19,Derby,Southampton,0.0,0.0,0.0,0.0,2.0,2.0,D
4,2000/01,2000-08-19,Leeds,Everton,0.0,0.0,0.0,0.0,2.0,0.0,H

In [6]:
prem_df.isnull().sum()

Season       0
MatchDate    0
HomeTeam     0
AwayTeam     0
Form3Home    0
Form5Home    0
Form3Away    0
Form5Away    0
FTHome       0
FTAway       0
FTResult     0
dtype: int64

In [7]:
prem_df.duplicated().sum()

np.int64(0)

In [8]:
prem_df["FTResult"].value_counts()

FTResult
H    4310
A    2782
D    2318
Name: count, dtype: int64

In [9]:
prem_df.describe()

,MatchDate,Form3Home,Form5Home,Form3Away,Form5Away,FTHome,FTAway
count,9410,9410.000000,9410.000000,9410.000000,9410.000000,9410.000000,9410.000000
mean,2013-01-31 21:39:40.361317,4.042189,6.823273,4.261955,7.065994,1.534431,1.183103
min,2000-08-19 00:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2006-12-09 00:00:00,2.000000,4.000000,3.000000,4.000000,1.000000,0.000000
50%,2013-01-30 00:00:00,4.000000,7.000000,4.000000,7.000000,1.000000,1.000000
75%,2019-03-30 00:00:00,6.000000,9.000000,6.000000,10.000000,2.000000,2.000000
max,2025-05-25 00:00:00,9.000000,15.000000,9.000000,15.000000,9.000000,9.000000
std,NaN,2.459152,3.419031,2.470471,3.398655,1.304820,1.157283

In [10]:
sorted(prem_df["HomeTeam"].unique())

['Arsenal',
 'Aston Villa',
 'Birmingham',
 'Blackburn',
 'Blackpool',
 'Bolton',
 'Bournemouth',
 'Bradford',
 'Brentford',
 'Brighton',
 'Burnley',
 'Cardiff',
 'Charlton',
 'Chelsea',
 'Coventry',
 'Crystal Palace',
 'Derby',
 'Everton',
 'Fulham',
 'Huddersfield',
 'Hull',
 'Ipswich',
 'Leeds',
 'Leicester',
 'Liverpool',
 'Luton',
 'Man City',
 'Man United',
 'Middlesbrough',
 'Newcastle',
 'Norwich',
 "Nott'm Forest",
 'Nottm Forest',
 'Portsmouth',
 'QPR',
 'Reading',
 'Sheffield United',
 'Southampton',
 'Stoke',
 'Sunderland',
 'Swansea',
 'Tottenham',
 'Watford',
 'West Brom',
 'West Ham',
 'Wigan',
 'Wolves']

In [11]:
sorted(prem_df["AwayTeam"].unique())

['Arsenal',
 'Aston Villa',
 'Birmingham',
 'Blackburn',
 'Blackpool',
 'Bolton',
 'Bournemouth',
 'Bradford',
 'Brentford',
 'Brighton',
 'Burnley',
 'Cardiff',
 'Charlton',
 'Chelsea',
 'Coventry',
 'Crystal Palace',
 'Derby',
 'Everton',
 'Fulham',
 'Huddersfield',
 'Hull',
 'Ipswich',
 'Leeds',
 'Leicester',
 'Liverpool',
 'Luton',
 'Man City',
 'Man United',
 'Middlesbrough',
 'Newcastle',
 'Norwich',
 "Nott'm Forest",
 'Nottm Forest',
 'Portsmouth',
 'QPR',
 'Reading',
 'Sheffield United',
 'Southampton',
 'Stoke',
 'Sunderland',
 'Swansea',
 'Tottenham',
 'Watford',
 'West Brom',
 'West Ham',
 'Wigan',
 'Wolves']

In [12]:
team_name_fixes = {
    "Nott'm Forest": "Nottingham Forest",
    "Nottm Forest": "Nottingham Forest"
}
prem_df["HomeTeam"] = prem_df["HomeTeam"].replace(team_name_fixes)
prem_df["AwayTeam"] = prem_df["AwayTeam"].replace(team_name_fixes)

sorted(prem_df["HomeTeam"].unique())

['Arsenal',
 'Aston Villa',
 'Birmingham',
 'Blackburn',
 'Blackpool',
 'Bolton',
 'Bournemouth',
 'Bradford',
 'Brentford',
 'Brighton',
 'Burnley',
 'Cardiff',
 'Charlton',
 'Chelsea',
 'Coventry',
 'Crystal Palace',
 'Derby',
 'Everton',
 'Fulham',
 'Huddersfield',
 'Hull',
 'Ipswich',
 'Leeds',
 'Leicester',
 'Liverpool',
 'Luton',
 'Man City',
 'Man United',
 'Middlesbrough',
 'Newcastle',
 'Norwich',
 'Nottingham Forest',
 'Portsmouth',
 'QPR',
 'Reading',
 'Sheffield United',
 'Southampton',
 'Stoke',
 'Sunderland',
 'Swansea',
 'Tottenham',
 'Watford',
 'West Brom',
 'West Ham',
 'Wigan',
 'Wolves']

In [13]:
prem_df.to_csv("../data/processed/clean_matches.csv", index=False)