In [1]:
import pandas as pd
df = pd.read_csv("../data/processed/clean_matches.csv")
df.head()

,MatchDate,HomeTeam,AwayTeam,HomeElo,AwayElo,Form3Home,Form5Home,Form3Away,Form5Away,FTHome,FTAway,FTResult
0,2015-08-08,Bournemouth,Aston Villa,1597.08,1580.38,7.0,13.0,3.0,6.0,0.0,1.0,A
1,2015-08-08,Chelsea,Swansea,1893.44,1673.08,4.0,10.0,3.0,9.0,2.0,2.0,D
2,2015-08-08,Everton,Watford,1709.04,1576.56,3.0,6.0,7.0,13.0,2.0,2.0,D
3,2015-08-08,Leicester,Sunderland,1636.10,1607.61,7.0,10.0,2.0,8.0,4.0,2.0,H
4,2015-08-08,Man United,Tottenham,1812.81,1733.16,5.0,5.0,6.0,7.0,1.0,0.0,H

# Feature engineering

In [2]:
team_history = df[["MatchDate", "HomeTeam", "AwayTeam", "FTHome", "FTAway"]].copy()

home = team_history[["MatchDate", "HomeTeam", "FTHome", "FTAway"]].copy()
home.columns = ["MatchDate", "Team", "GoalsScored", "GoalsConceded"]

away = team_history[["MatchDate", "AwayTeam", "FTHome", "FTAway"]].copy()
away.columns = ["MatchDate", "Team", "GoalsConceded", "GoalsScored"]

team_history = pd.concat([home, away])
team_history = team_history.sort_values(["Team", "MatchDate"])
team_history.head(10)

     MatchDate     Team  GoalsScored  GoalsConceded
6   2015-08-09  Arsenal          0.0            2.0
17  2015-08-16  Arsenal          2.0            1.0
29  2015-08-24  Arsenal          0.0            0.0
35  2015-08-29  Arsenal          1.0            0.0
40  2015-09-12  Arsenal          2.0            0.0
52  2015-09-19  Arsenal          0.0            2.0
60  2015-09-26  Arsenal          5.0            2.0
77  2015-10-04  Arsenal          3.0            0.0
86  2015-10-17  Arsenal          3.0            0.0
90  2015-10-24  Arsenal          2.0            1.0

In [3]:
team_history["AvgGoalsScored5"] = (
    team_history
    .groupby("Team")["GoalsScored"]
    .transform(lambda x: x.shift(1).rolling(5).mean())
)

team_history["AvgGoalsConceded5"] = (
    team_history
    .groupby("Team")["GoalsConceded"]
    .transform(lambda x: x.shift(1).rolling(5).mean())
)

team_history.head(20)

,MatchDate,Team,GoalsScored,GoalsConceded,AvgGoalsScored5,AvgGoalsConceded5
6,2015-08-09,Arsenal,0.0,2.0,NaN,NaN
17,2015-08-16,Arsenal,2.0,1.0,NaN,NaN
29,2015-08-24,Arsenal,0.0,0.0,NaN,NaN
35,2015-08-29,Arsenal,1.0,0.0,NaN,NaN
40,2015-09-12,Arsenal,2.0,0.0,NaN,NaN
52,2015-09-19,Arsenal,0.0,2.0,1.0,0.6
60,2015-09-26,Arsenal,5.0,2.0,1.0,0.6
77,2015-10-04,Arsenal,3.0,0.0,1.6,0.8
86,2015-10-17,Arsenal,3.0,0.0,2.2,0.8
90,2015-10-24,Arsenal,2.0,1.0,2.6,0.8
104,2015-10-31,Arsenal,3.0,0.0,2.6,1.0
117,2015-11-08,Arsenal,1.0,1.0,3.2,0.6
127,2015-11-21,Arsenal,1.0,2.0,2.4,0.4
137,2015-11-29,Arsenal,1.0,1.0,2.0,0.8
140,2015-12-05,Arsenal,3.0,1.0,1.6,1.0
156,2015-12-13,Arsenal,2.0,0.0,1.8,1.0
169,2015-12-21,Arsenal,2.0,1.0,1.6,1.0
176,2015-12-26,Arsenal,0.0,4.0,1.8,1.0
180,2015-12-28,Arsenal,2.0,0.0,1.6,1.4
190,2016-01-02,Arsenal,1.0,0.0,1.8,1.2

In [4]:
home_stats = team_history[["MatchDate", "Team", "AvgGoalsScored5", "AvgGoalsConceded5"]].copy()
home_stats = home_stats.rename(columns={
    "Team": "HomeTeam",
    "AvgGoalsScored5": "HomeAvgGoalsScored5",
    "AvgGoalsConceded5": "HomeAvgGoalsConceded5"
})

away_stats = team_history[[
    "MatchDate",
    "Team",
    "AvgGoalsScored5",
    "AvgGoalsConceded5"
]].copy()
away_stats = away_stats.rename(columns={
    "Team": "AwayTeam",
    "AvgGoalsScored5": "AwayAvgGoalsScored5",
    "AvgGoalsConceded5": "AwayAvgGoalsConceded5"
})

df = df.merge(
    home_stats,
    on=["MatchDate", "HomeTeam"],
    how="left"
)

df = df.merge(
    away_stats,
    on=["MatchDate", "AwayTeam"],
    how="left"
)

In [5]:
df.head(60)

,MatchDate,HomeTeam,AwayTeam,HomeElo,AwayElo,Form3Home,Form5Home,Form3Away,Form5Away,FTHome,FTAway,FTResult,HomeAvgGoalsScored5,HomeAvgGoalsConceded5,AwayAvgGoalsScored5,AwayAvgGoalsConceded5
0,2015-08-08,Bournemouth,Aston Villa,1597.08,1580.38,7.0,13.0,3.0,6.0,0.0,1.0,A,NaN,NaN,NaN,NaN
1,2015-08-08,Chelsea,Swansea,1893.44,1673.08,4.0,10.0,3.0,9.0,2.0,2.0,D,NaN,NaN,NaN,NaN
2,2015-08-08,Everton,Watford,1709.04,1576.56,3.0,6.0,7.0,13.0,2.0,2.0,D,NaN,NaN,NaN,NaN
3,2015-08-08,Leicester,Sunderland,1636.10,1607.61,7.0,10.0,2.0,8.0,4.0,2.0,H,NaN,NaN,NaN,NaN
4,2015-08-08,Man United,Tottenham,1812.81,1733.16,5.0,5.0,6.0,7.0,1.0,0.0,H,NaN,NaN,NaN,NaN
5,2015-08-08,Norwich,Crystal Palace,1617.68,1649.26,4.0,10.0,6.0,6.0,1.0,3.0,A,NaN,NaN,NaN,NaN
6,2015-08-09,Arsenal,West Ham,1853.70,1609.12,5.0,8.0,0.0,4.0,0.0,2.0,A,NaN,NaN,NaN,NaN
7,2015-08-09,Newcastle,Southampton,1590.10,1717.73,4.0,4.0,3.0,4.0,2.0,2.0,D,NaN,NaN,NaN,NaN
8,2015-08-09,Stoke,Liverpool,1700.78,1755.30,7.0,8.0,1.0,4.0,0.0,1.0,A,NaN,NaN,NaN,NaN
9,2015-08-10,West Brom,Man City,1638.09,1884.95,4.0,8.0,9.0,15.0,0.0,3.0,A,NaN,NaN,NaN,NaN
10,2015-08-14,Aston Villa,Man United,1580.38,1812.81,3.0,9.0,5.0,8.0,0.0,1.0,A,NaN,NaN,NaN,NaN
11,2015-08-15,Southampton,Everton,1715.52,1701.66,4.0,4.0,4.0,4.0,0.0,3.0,A,NaN,NaN,NaN,NaN
12,2015-08-15,Sunderland,Norwich,1596.54,1602.95,1.0,5.0,4.0,7.0,1.0,3.0,A,NaN,NaN,NaN,NaN
13,2015-08-15,Swansea,Newcastle,1677.19,1589.81,1.0,7.0,4.0,5.0,2.0,0.0,H,NaN,NaN,NaN,NaN
14,2015-08-15,Tottenham,Stoke,1725.91,1690.36,6.0,6.0,4.0,7.0,2.0,2.0,D,NaN,NaN,NaN,NaN
15,2015-08-15,Watford,West Brom,1578.99,1629.60,5.0,11.0,3.0,7.0,0.0,0.0,D,NaN,NaN,NaN,NaN
16,2015-08-15,West Ham,Leicester,1618.05,1642.21,3.0,6.0,7.0,13.0,1.0,2.0,A,NaN,NaN,NaN,NaN
17,2015-08-16,Crystal Palace,Arsenal,1659.04,1829.77,9.0,9.0,4.0,5.0,1.0,2.0,A,NaN,NaN,NaN,NaN
18,2015-08-16,Man City,Chelsea,1888.50,1884.38,9.0,15.0,4.0,8.0,3.0,0.0,H,NaN,NaN,NaN,NaN
19,2015-08-17,Liverpool,Bournemouth,1760.78,1584.88,3.0,7.0,6.0,10.0,1.0,0.0,H,NaN,NaN,NaN,NaN
20,2015-08-22,Crystal Palace,Aston Villa,1659.04,1583.72,6.0,9.0,3.0,6.0,2.0,1.0,H,NaN,NaN,NaN,NaN
21,2015-08-22,Leicester,Tottenham,1642.21,1725.91,9.0,13.0,4.0,7.0,1.0,1.0,D,NaN,NaN,NaN,NaN
22,2015-08-22,Man United,Newcastle,1819.01,1589.81,7.0,11.0,4.0,5.0,0.0,0.0,D,NaN,NaN,NaN,NaN
23,2015-08-22,Norwich,Stoke,1602.95,1690.36,6.0,7.0,4.0,8.0,1.0,1.0,D,NaN,NaN,NaN,NaN
24,2015-08-22,Sunderland,Swansea,1596.54,1677.19,0.0,2.0,4.0,7.0,1.0,1.0,D,NaN,NaN,NaN,NaN
25,2015-08-22,West Ham,Bournemouth,1618.05,1584.88,3.0,3.0,3.0,7.0,3.0,4.0,A,NaN,NaN,NaN,NaN
26,2015-08-23,Everton,Man City,1701.66,1888.50,4.0,7.0,9.0,15.0,0.0,2.0,A,NaN,NaN,NaN,NaN
27,2015-08-23,Watford,Southampton,1578.99,1715.52,3.0,9.0,1.0,4.0,0.0,0.0,D,NaN,NaN,NaN,NaN
28,2015-08-23,West Brom,Chelsea,1629.60,1884.38,1.0,5.0,4.0,5.0,2.0,3.0,A,NaN,NaN,NaN,NaN
29,2015-08-24,Arsenal,Liverpool,1829.77,1760.78,6.0,8.0,6.0,7.0,0.0,0.0,D,NaN,NaN,NaN,NaN
30,2015-08-29,Aston Villa,Sunderland,1583.72,1596.54,3.0,3.0,1.0,2.0,2.0,2.0,D,NaN,NaN,NaN,NaN
31,2015-08-29,Bournemouth,Leicester,1584.88,1642.21,3.0,9.0,7.0,11.0,1.0,1.0,D,NaN,NaN,NaN,NaN
32,2015-08-29,Chelsea,Crystal Palace,1884.38,1659.04,4.0,7.0,6.0,12.0,1.0,2.0,A,NaN,NaN,NaN,NaN
33,2015-08-29,Liverpool,West Ham,1760.78,1618.05,7.0,7.0,3.0,3.0,0.0,3.0,A,NaN,NaN,NaN,NaN
34,2015-08-29,Man City,Watford,1888.50,1578.99,9.0,15.0,3.0,7.0,2.0,0.0,H,NaN,NaN,NaN,NaN
35,2015-08-29,Newcastle,Arsenal,1589.81,1829.77,2.0,5.0,4.0,8.0,0.0,1.0,A,NaN,NaN,NaN,NaN
36,2015-08-29,Stoke,West Brom,1690.36,1629.60,2.0,6.0,1.0,4.0,0.0,1.0,A,NaN,NaN,NaN,NaN
37,2015-08-29,Tottenham,Everton,1725.91,1701.66,2.0,8.0,4.0,7.0,0.0,0.0,D,NaN,NaN,NaN,NaN
38,2015-08-30,Southampton,Norwich,1715.52,1602.95,2.0,5.0,4.0,8.0,3.0,0.0,H,NaN,NaN,NaN,NaN
39,2015-08-30,Swansea,Man United,1677.19,1819.01,5.0,5.0,7.0,9.0,2.0,1.0,H,NaN,NaN,NaN,NaN
40,2015-09-12,Arsenal,Stoke,1831.82,1677.62,7.0,10.0,2.0,5.0,2.0,0.0,H,NaN,NaN,NaN,NaN
41,2015-09-12,Crystal Palace,Man City,1670.35,1905.42,6.0,12.0,9.0,15.0,0.0,1.0,A,NaN,NaN,NaN,NaN
42,2015-09-12,Everton,Chelsea,1710.13,1858.87,4.0,5.0,3.0,7.0,3.0,1.0,H,NaN,NaN,NaN,NaN
43,2015-09-12,Man United,Liverpool,1807.87,1740.88,4.0,8.0,4.0,7.0,3.0,1.0,H,NaN,NaN,NaN,NaN
44,2015-09-12,Norwich,Bournemouth,1603.77,1588.95,4.0,7.0,4.0,7.0,3.0,1.0,H,NaN,NaN,NaN,NaN
45,2015-09-12,Watford,Swansea,1575.84,1689.91,2.0,4.0,7.0,8.0,1.0,0.0,H,NaN,NaN,NaN,NaN
46,2015-09-12,West Brom,Southampton,1633.90,1684.07,4.0,4.0,4.0,5.0,0.0,0.0,D,NaN,NaN,NaN,NaN
47,2015-09-13,Leicester,Aston Villa,1648.12,1574.19,5.0,11.0,1.0,4.0,3.0,2.0,H,NaN,NaN,NaN,NaN
48,2015-09-13,Sunderland,Tottenham,1583.06,1717.92,2.0,2.0,3.0,6.0,0.0,1.0,A,NaN,NaN,NaN,NaN
49,2015-09-14,West Ham,Newcastle,1619.19,1583.21,3.0,6.0,1.0,5.0,2.0,0.0,H,NaN,NaN,NaN,NaN
50,2015-09-19,Aston Villa,West Brom,1569.08,1634.21,1.0,4.0,4.0,5.0,0.0,1.0,A,1.2,1.6,0.6,1.2
51,2015-09-19,Bournemouth,Sunderland,1579.70,1577.37,4.0,4.0,2.0,2.0,2.0,0.0,H,1.2,1.8,1.2,2.2
52,2015-09-19,Chelsea,Arsenal,1843.40,1837.04,3.0,4.0,7.0,10.0,2.0,0.0,H,1.4,2.4,1.0,0.6
53,2015-09-19,Man City,West Ham,1908.94,1627.77,9.0,15.0,6.0,9.0,1.0,2.0,A,2.2,0.0,2.2,1.2
54,2015-09-19,Newcastle,Watford,1574.63,1585.95,1.0,2.0,4.0,6.0,1.0,2.0,A,0.4,1.4,0.6,0.8
55,2015-09-19,Stoke,Leicester,1672.41,1653.22,1.0,2.0,5.0,11.0,2.0,2.0,D,0.6,1.4,2.2,1.4
56,2015-09-19,Swansea,Everton,1679.80,1725.60,4.0,8.0,4.0,8.0,0.0,0.0,D,1.4,1.0,1.6,1.0
57,2015-09-20,Liverpool,Norwich,1733.26,1613.03,1.0,7.0,4.0,7.0,1.0,1.0,D,0.6,1.2,1.6,1.8
58,2015-09-20,Southampton,Man United,1683.76,1815.49,5.0,6.0,4.0,10.0,2.0,3.0,A,1.0,1.0,1.2,0.6
59,2015-09-20,Tottenham,Crystal Palace,1723.61,1666.83,5.0,6.0,6.0,9.0,1.0,0.0,H,0.8,0.8,1.6,1.2

In [6]:
df = df.dropna(subset=[
    "HomeAvgGoalsScored5",
    "HomeAvgGoalsConceded5",
    "AwayAvgGoalsScored5",
    "AwayAvgGoalsConceded5"
])
df.head()

,MatchDate,HomeTeam,AwayTeam,HomeElo,AwayElo,Form3Home,Form5Home,Form3Away,Form5Away,FTHome,FTAway,FTResult,HomeAvgGoalsScored5,HomeAvgGoalsConceded5,AwayAvgGoalsScored5,AwayAvgGoalsConceded5
50,2015-09-19,Aston Villa,West Brom,1569.08,1634.21,1.0,4.0,4.0,5.0,0.0,1.0,A,1.2,1.6,0.6,1.2
51,2015-09-19,Bournemouth,Sunderland,1579.70,1577.37,4.0,4.0,2.0,2.0,2.0,0.0,H,1.2,1.8,1.2,2.2
52,2015-09-19,Chelsea,Arsenal,1843.40,1837.04,3.0,4.0,7.0,10.0,2.0,0.0,H,1.4,2.4,1.0,0.6
53,2015-09-19,Man City,West Ham,1908.94,1627.77,9.0,15.0,6.0,9.0,1.0,2.0,A,2.2,0.0,2.2,1.2
54,2015-09-19,Newcastle,Watford,1574.63,1585.95,1.0,2.0,4.0,6.0,1.0,2.0,A,0.4,1.4,0.6,0.8

In [7]:
df = df.drop(columns=["FTHome", "FTAway", "MatchDate", "HomeTeam", "AwayTeam"])
df.head()

,HomeElo,AwayElo,Form3Home,Form5Home,Form3Away,Form5Away,FTResult,HomeAvgGoalsScored5,HomeAvgGoalsConceded5,AwayAvgGoalsScored5,AwayAvgGoalsConceded5
50,1569.08,1634.21,1.0,4.0,4.0,5.0,A,1.2,1.6,0.6,1.2
51,1579.70,1577.37,4.0,4.0,2.0,2.0,H,1.2,1.8,1.2,2.2
52,1843.40,1837.04,3.0,4.0,7.0,10.0,H,1.4,2.4,1.0,0.6
53,1908.94,1627.77,9.0,15.0,6.0,9.0,A,2.2,0.0,2.2,1.2
54,1574.63,1585.95,1.0,2.0,4.0,6.0,A,0.4,1.4,0.6,0.8

In [8]:
df["EloDifference"] = df["HomeElo"] - df["AwayElo"]
df["FormDifference"] = df["Form5Home"] - df["Form5Away"]
df["GoalsScoredDifference5"] = (
    df["HomeAvgGoalsScored5"] -
    df["AwayAvgGoalsScored5"]
)

df["GoalsConcededDifference5"] = (
    df["HomeAvgGoalsConceded5"] -
    df["AwayAvgGoalsConceded5"]
)
df.head()

,HomeElo,AwayElo,Form3Home,Form5Home,Form3Away,Form5Away,FTResult,HomeAvgGoalsScored5,HomeAvgGoalsConceded5,AwayAvgGoalsScored5,AwayAvgGoalsConceded5,EloDifference,FormDifference,GoalsScoredDifference5,GoalsConcededDifference5
50,1569.08,1634.21,1.0,4.0,4.0,5.0,A,1.2,1.6,0.6,1.2,-65.13,-1.0,0.6,0.4
51,1579.70,1577.37,4.0,4.0,2.0,2.0,H,1.2,1.8,1.2,2.2,2.33,2.0,0.0,-0.4
52,1843.40,1837.04,3.0,4.0,7.0,10.0,H,1.4,2.4,1.0,0.6,6.36,-6.0,0.4,1.8
53,1908.94,1627.77,9.0,15.0,6.0,9.0,A,2.2,0.0,2.2,1.2,281.17,6.0,0.0,-1.2
54,1574.63,1585.95,1.0,2.0,4.0,6.0,A,0.4,1.4,0.6,0.8,-11.32,-4.0,-0.2,0.6

In [25]:
x = df.drop("FTResult", axis=1)
y = df["FTResult"]

In [10]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

y = encoder.fit_transform(y)

# Splitting the data

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, shuffle=False)

# Normalising the data

In [12]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [13]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(2943, 14)
(736, 14)
(2943,)
(736,)

# Train the model

In [14]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000, class_weight="balanced")
model.fit(X_train, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [15]:
y_pred = model.predict(X_test)

# Evaluation of the model

In [16]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_pred, y_test)
print(accuracy)

0.49592391304347827

In [17]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.52      0.57      0.55       248
           1       0.20      0.19      0.20       168
           2       0.62      0.60      0.61       320

    accuracy                           0.50       736
   macro avg       0.45      0.45      0.45       736
weighted avg       0.49      0.50      0.49       736

In [18]:
probabilities = model.predict_proba(X_test)

print(probabilities[0])

[0.46701378 0.32424207 0.20874415]

In [19]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[142  59  47]
 [ 67  32  69]
 [ 62  67 191]]

In [20]:
df["FTResult"].value_counts(normalize=True)

FTResult
H    0.447404
A    0.321555
D    0.231041
Name: proportion, dtype: float64

## Testing another model

In [23]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    class_weight="balanced"
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

In [24]:
from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.54      0.55      0.55       248
           1       0.14      0.03      0.05       168
           2       0.55      0.77      0.64       320

    accuracy                           0.53       736
   macro avg       0.41      0.45      0.41       736
weighted avg       0.45      0.53      0.47       736

[[137  12  99]
 [ 60   5 103]
 [ 56  19 245]]

In [26]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_pred, y_test)
print(accuracy)

0.5258152173913043